// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutoDismissController from "./auto_dismiss_controller";
application.register("auto-dismiss", AutoDismissController);

import InputController from "./input_controller";
application.register("input", InputController);

import PreviewController from "./preview_controller";
application.register("preview", PreviewController);
