development:
  adapter: redis
  url: <%= Rails.application.config.x.redis_url %>
  channel_prefix: pulse_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.config.x.redis_url %>
  channel_prefix: pulse_production
